apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress-container
          image: wordpress:php8.3-apache
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
              name: http-port
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service.default.svc.cluster.local
            - name: WORDPRESS_DB_USER
              value: db-user
            - name: WORDPRESS_DB_PASSWORD
              value: db-pass
            - name: WORDPRESS_DB_NAME
              value: wordpress-db
          volumeMounts:
            - mountPath: /etc/www/html
              name: wordpress-volume
      volumes:
        - name: wordpress-volume
          persistentVolumeClaim:
            claimName: wordpress-pvc
      securityContext:
        fsGroup: 0 
        runAsUser: 0